### PR TITLE
Optional schema version name

### PR DESCRIPTION
**Pull request by adiweiss**

### CODE REVIEW

**Comment by adiweiss** [comment]
@lopezator any news here?

**Comment by lopezator** [comment]
Sorry, I've been off for summer a few weeks.

I'll check this in next few days.

Thanks!

**Comment by lopezator** [comment]
Wouldn't be this enough @adiweiss ?

https://github.com/lopezator/migrator/commit/3d4f8d86f7b48350be50ec87fe62e80d0bc171b7#diff-664808b21216aca953012ad84b052c1d

IMHO this is too much for just being able to set the tableName.

Please take a look and tell me what you think, and if this would be enough for you.

Thank you for work & interest!

**Comment by adiweiss** [comment]
> Wouldn't be this enough @adiweiss ?
> 
> [0caecc0](https://github.com/lopezator/migrator/commit/0caecc0622aabeb674bf808361178d676970a429)
> 
> IMHO this is too much for just being able to set the tableName.
> 
> Please take a look and tell me what you think, and if this would be enough for you.
> 
> Thank you for work & interest!

@lopezator thanks for your review :) my implementation supports  3rd party lib  migrations in a different migrations table

**Comment by lopezator** [comment]
Hello @adiweiss I think I am missing something here. 

Can you provide more context of why the linked commit (simply exporting the const to a var), wouldn't work for you?

This way, you could set the migrator table from outside using `migrator.TableName` wouldn't that suffice for you?

**Comment by lopezator** [comment]
I'll check and prepare an example though.

**Comment by adiweiss** [comment]
@lopezator  if for example my project uses "migrator" with TableA and it imports a library the uses TableB then the const->var implementation wont work...

**Comment by lopezator** [comment]
@adiweiss Thank you for your efforts!

We've been thinking about this and my colleague @glerchundi has been working on a functional approach in order to be able to inject more options for the future in the case we need more without breaking the API.

Please, tell us what you think and if this will work for you!

**Comment by adiweiss** [comment]
> @adiweiss Thank you again for your effort!
> 
> Inspired by your work, we've been thinking about this, and my colleague @glerchundi came with this opts functional approach in #18 to be able to inject more options for the future without breaking the API.
> 
> Please, tell us what you think and if this will work for you!

awesome thanks!

**Comment by lopezator** [comment]
Glad you are ok with this!

I'll merge #18 then. Thanks for your work.

**Pull request closed without merging**
